### PR TITLE
Translate Readme

### PR DESCRIPTION
**Pull request by Erfankam**
I have translated readme file. I also omit some personal links did not belongs to the main contents.
Please merge this changes. Thanks

### CODE REVIEW

**Comment by Erfankam** [comment]
@pouriamokhtari Please merge this changes in order to avoid long list of changes in merging queue. Thanks.

**Comment by p0m0h3** [comment]
Thanks for the PR, I'm not sure why we need to have Persian README. Any particular reason?

**Comment by Erfankam** [comment]
> Thanks for the PR, I'm not sure why we need to have Persian README. Any particular reason?

I think it can help us to clarify Persian specific translation goal and methods besides it s not a part of original English book, so it belongs to Persian translation like a cover.

**Comment by Erfankam** [comment]
@pouriamokhtari Thanks for merging.

**Pull request merged**
